version: '3'

services:
    app:
        build:
            context: .
        ports:
            - "5000:5000"
        volumes:
            - ./api:/api
        command: python -u app/run.py
        links: 
            - db
    db:
        image: mongo:latest